#ifndef LIVE_VIDEO_STREAM_VERSION_HPP
#define LIVE_VIDEO_STREAM_VERSION_HPP

#define LIVE_VIDEO_STREAM_VERSION_MAJOR 0
#define LIVE_VIDEO_STREAM_VERSION_MINOR 1
#define LIVE_VIDEO_STREAM_VERSION_PATCH 0

#define LIVE_VIDEO_STREAM_VERSION 0.1.0

#endif //LIVE_VIDEO_STREAM_VERSION_HPP
